defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

base_path: ""

kramdown:
  input: GFM
  auto_ids: true
highlighter: pygments

organization_name: SENSE Lab
title: SENSE Lab at ASU SESE

exclude: [vendor]

menu:
  - name: Current Projects
    link: projects
  - name: People
    link: people

tags: a,b,c,d
